name: Build APK

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build APK
        id: build
        uses: ArtemSBulgakov/buildozer-action@v1.5.0
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ steps.build.outputs.apk-name }}
          path: bin/*.apk*
